### ISSUE TITLE
Prototype: coss components in raya's registry, Studio preview, and export

### ISSUE THREAD

**Issue by AltManic** [AltManic/raya#25]
## Question

Prove — concretely and roughly — how a coss component lands in raya: registry item, Studio preview, token switching, dark mode, HugeIcons substitution, and consumer build. Prototype, not production: throwaway artifacts under `prototypes/`.

Suggested slice (adjust as you learn):

- Port coss's **Button**, **Input** (+ Field), and **Card** (coss `e937becd…`) into raya's registry format, keeping coss's Tailwind/cva markup; swap lucide icons for HugeIcons through raya's icon mechanism (`registry/internal/icon-placeholder.tsx`); wire coss's theme tokens (MIT provenance per the copy-source audit ticket).
- Render them in the Studio under System switching + dark mode; confirm token switching still drives them.
- Run `shadcn registry validate` and `shadcn build`; note what the roundtrip fixture (`tools/roundtrip-fixture/`) would need.
- Record every friction point: Base UI version, class conflicts, icon substitution, CSS layering, Next-specific residue, cva/knob interactions.

Deliverable: prototype artifacts + a findings comment on this ticket that the sibling tickets (Studio shell, System model, token vocabulary) can lean on. Reacting to something concrete is the point — surface screenshots or code snippets.

Blocked by the copy-source audit and integration audit tickets.

**Comment by AltManic** [comment]
## Findings — coss components land in raya (prototype)

Branch: [prototype/coss-components](https://github.com/AltManic/raya/tree/prototype/coss-components) @ `4f6dade` · coss pinned `e937bec`, MIT surface only
Try it: `npm install && npm run dev` → `http://localhost:3000/coss-proto` (System + dark toggles in the header)
README + files: [`prototypes/coss-components/`](https://github.com/AltManic/raya/blob/prototype/coss-components/prototypes/coss-components/README.md)

**1. The port is mechanical — three deltas from coss's source.** `utils`, `spinner`, `button`, `input`, `field`, `card` ported with only (a) import-path adaptation, (b) lucide → `IconPlaceholder`, (c) nothing else. Zero class-string changes were needed; every utility resolved under raya's Tailwind + core bridge. All 36 registry items validate; `shadcn build` emits `public/r/coss-*.json`.

**2. One bridge gap for this slice: `--font-heading`.** coss's Card/Dialog titles use `font-heading`; raya's `@theme inline` lacked it. Added `--font-heading: var(--font-sans)` to `core.css` (MIT-published at coss's `styling.mdx` + `registry-styles.ts`). Every other token this slice touches already exists in raya's Systems.

**3. Icon substitution works end-to-end — with two sharp edges.** Authored with raya's multi-library placeholders; the roundtrip fixture shows the CLI emitting `import { HugeiconsIcon } from "@hugeicons/react"` + `import { Loading03Icon } from "@hugeicons/core-free-icons"`. Edges: (a) never reference `typeof IconPlaceholder` in an exported type — the CLI strips the import and leaves a dangling type (the fixture caught exactly this: `Cannot find name 'IconPlaceholder'`); (b) don't spread broad span props onto the placeholder — after install they land on an SVG component whose event-target variance rejects them. `SpinnerProps = { className?: string }` is the narrowed fix. Rules recorded in the README and the component comments.

**4. Base UI 1.8.0 bump is safe for this slice — no code changes.** The preview and fixture compile, SSR-render, and build on 1.8.0. (#24's `createItems` requirement is Combobox-only, not in this slice.)

**5. The roundtrip fixture needed no structural change.** Proto items installed; item `dependencies` auto-installed `class-variance-authority` / `clsx` / `tailwind-merge`; the icon transform ran; `tsc --noEmit` + `vite build` pass. Two fixture notes for the real port: it hardcodes `@hugeicons/react ^1.0.0` / `core-free-icons ^1.0.0` (npm resolved 1.1.10 / 2.0.0 — pin to coss's `^1.1.1` / `^2.0.0`), and the icon-name values in placeholders must be real hugeicons exports (fixture typechecks them).

**6. What this means for the sibling tickets.** System model (#27): Systems-as-token-presets is sufficient — none of these components read knob vars. Token vocabulary (#28): the slice needs none of the new colors (info/success/warning, code, sidebar); that work is still the engine for the full 54. Studio shell (#26): coss components sit cleanly inside the existing shell under System switching + dark mode.

No screenshots this session (desktop browser not connected); SSR HTML was verified to contain the rendered Card/Button/Field under `data-raya="baseline"`.

**Comment by AltManic** [comment]
Resolved by the findings above — the port is mechanical, Base UI 1.8 is safe, the fixture needs no structural change, and the slice confirms Systems-as-token-presets. Answer indexed on the map.
